export const dataMock = [
  {
    name: "Hangzhou Head Office",
    type: 1, // 1 company 2 branch company 3 department
    parentId: 0,
    sort: 0,
    leaderUserId: 1,
    phone: "123456789",
    email: "aaa@qq.com",
    status: 0,
    id: 100,
    createTime: "2020-10-30",
    remark: "remark, remark, remark, remark, remark"
  },
  {
    name: "Zhengzhou Branch",
    type: 2,
    parentId: 100,
    sort: 1,
    leaderUserId: 104,
    phone: "123456789",
    email: "aaa@qq.com",
    status: 0,
    id: 101,
    createTime: "2020-10-30",
    remark: "remark, remark, remark, remark, remark"
  },
  {
    name: "R & D department",
    type: 3,
    parentId: 101,
    sort: 1,
    leaderUserId: 104,
    phone: "123456789",
    email: "aaa@qq.com",
    status: 0,
    id: 103,
    createTime: "2020-10-30",
    remark: "remark, remark, remark, remark, remark"
  },
  {
    name: "marketing department",
    type: 3,
    parentId: 102,
    sort: 1,
    leaderUserId: null,
    phone: "123456789",
    email: "aaa@qq.com",
    status: 0,
    id: 108,
    createTime: "2020-10-30",
    remark: "remark, remark, remark, remark, remark"
  },
  {
    name: "Shenzhen Branch",
    type: 2,
    parentId: 100,
    sort: 2,
    leaderUserId: null,
    phone: "123456789",
    email: "aaa@qq.com",
    status: 0,
    id: 102,
    createTime: "2020-10-30",
    remark: "remark, remark, remark, remark, remark"
  },
  {
    name: "marketing department",
    type: 3,
    parentId: 101,
    sort: 2,
    leaderUserId: null,
    phone: "123456789",
    email: "aaa@qq.com",
    status: 1,
    id: 104,
    createTime: "2020-10-30",
    remark: "remark, remark, remark, remark, remark"
  },
  {
    name: "financial department",
    type: 3,
    parentId: 102,
    sort: 2,
    leaderUserId: null,
    phone: "123456789",
    email: "aaa@qq.com",
    status: 0,
    id: 109,
    createTime: "2020-10-30",
    remark: "remark, remark, remark, remark, remark"
  },
  {
    name: "testing department",
    type: 3,
    parentId: 101,
    sort: 3,
    leaderUserId: null,
    phone: "123456789",
    email: "aaa@qq.com",
    status: 0,
    id: 105,
    createTime: "2020-10-30",
    remark: "remark, remark, remark, remark, remark"
  },
  {
    name: "financial department",
    type: 3,
    parentId: 101,
    sort: 4,
    leaderUserId: 103,
    phone: "123456789",
    email: "aaa@qq.com",
    status: 1,
    id: 106,
    createTime: "2020-10-30",
    remark: "remark, remark, remark, remark, remark"
  },
  {
    name: "Operation department",
    type: 3,
    parentId: 101,
    sort: 5,
    leaderUserId: null,
    phone: "123456789",
    email: "aaa@qq.com",
    status: 0,
    id: 107,
    createTime: "2020-10-30",
    remark: "remark, remark, remark, remark, remark"
  },
  {
    name: "Maintenance department",
    type: 3,
    parentId: 101,
    sort: 5,
    leaderUserId: null,
    phone: "123456789",
    email: "aaa@qq.com",
    status: 0,
    id: 107,
    createTime: "2020-10-30",
    remark: "remark, remark, remark, remark, remark"
  }
];
